# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZHYMantleTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'Mantle', '~> 2.1.0'
  # Pods for ZHYMantleTest

end
